// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDiWdaY3ZOfcwVdN-69qUVGreHowpveetI',
    appId: '1:661408636446:web:d5263b38d829f61e0a580f',
    messagingSenderId: '661408636446',
    projectId: 'medicamentos-pos',
    authDomain: 'medicamentos-pos.firebaseapp.com',
    storageBucket: 'medicamentos-pos.firebasestorage.app',
    measurementId: 'G-7T9QNVKK5J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMqiLY08ZYI3zZC_KyQ0NCRea_jwqfo78',
    appId: '1:661408636446:android:7b0ddc456bc9e5c00a580f',
    messagingSenderId: '661408636446',
    projectId: 'medicamentos-pos',
    storageBucket: 'medicamentos-pos.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDebyaIKELMfKnCCOqS0InMJWwJrjPx11g',
    appId: '1:661408636446:ios:353fb81e5e2fdc290a580f',
    messagingSenderId: '661408636446',
    projectId: 'medicamentos-pos',
    storageBucket: 'medicamentos-pos.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplicationMedicamento',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDebyaIKELMfKnCCOqS0InMJWwJrjPx11g',
    appId: '1:661408636446:ios:353fb81e5e2fdc290a580f',
    messagingSenderId: '661408636446',
    projectId: 'medicamentos-pos',
    storageBucket: 'medicamentos-pos.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplicationMedicamento',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDiWdaY3ZOfcwVdN-69qUVGreHowpveetI',
    appId: '1:661408636446:web:bea29111691ca96d0a580f',
    messagingSenderId: '661408636446',
    projectId: 'medicamentos-pos',
    authDomain: 'medicamentos-pos.firebaseapp.com',
    storageBucket: 'medicamentos-pos.firebasestorage.app',
    measurementId: 'G-7MWBMVYX87',
  );
}
